package com.otbs.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import lombok.Getter;

@Getter
@Service
public class BillEmailService {
//	 @Value("${spring.mail.username}")
     private String senderEmail = "sivarajc357@gmail.com";
	
//	 @Value("${spring.mail.password}")
     private String senderPassword = "tihuoneubjpnvmty"; // Use App Password if 2FA is enabled
     // HTML content for the email body
     private String billCreating = "<!DOCTYPE html>"
     + "<html>"
     + "<head>"
     + "    <title>Bill Notification</title>"
     + "    <style>"
     + "        body {"
     + "            font-family: Arial, sans-serif;"
     + "            margin: 0;"
     + "            padding: 0;"
     + "            background-color: #f4f4f4;"
     + "        }"
     + "        .email-container {"
     + "            max-width: 600px;"
     + "            margin: 20px auto;"
     + "            background-color: #ffffff;"
     + "            border: 1px solid #e0e0e0;"
     + "            border-radius: 8px;"
     + "            overflow: hidden;"
     + "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);"
     + "        }"
     + "        .header {"
     + "            background-color: #4CAF50;"
     + "            color: #ffffff;"
     + "            text-align: center;"
     + "            padding: 20px;"
     + "            font-size: 24px;"
     + "        }"
     + "        .content {"
     + "            padding: 20px;"
     + "            color: #333333;"
     + "        }"
     + "        .content p {"
     + "            margin: 10px 0;"
     + "            font-size: 16px;"
     + "            line-height: 1.5;"
     + "        }"
     + "        .bill-details {"
     + "            margin: 20px 0;"
     + "            border-collapse: collapse;"
     + "            width: 100%;"
     + "        }"
     + "        .bill-details th, .bill-details td {"
     + "            border: 1px solid #dddddd;"
     + "            text-align: left;"
     + "            padding: 8px;"
     + "        }"
     + "        .bill-details th {"
     + "            background-color: #f2f2f2;"
     + "        }"
     + "        .footer {"
     + "            background-color: #f2f2f2;"
     + "            color: #777777;"
     + "            text-align: center;"
     + "            padding: 15px;"
     + "            font-size: 12px;"
     + "        }"
     + "        .button {"
     + "            display: inline-block;"
     + "            margin: 20px auto;"
     + "            padding: 10px 20px;"
     + "            font-size: 16px;"
     + "            color: #ffffff;"
     + "            background-color: #4CAF50;"
     + "            text-decoration: none;"
     + "            border-radius: 5px;"
     + "            text-align: center;"
     + "        }"
     + "    </style>"
     + "</head>"
     + "<body>"
     + "    <div class=\"email-container\">"
     + "        <!-- Header -->"
     + "        <div class=\"header\">"
     + "            <strong>Your Bill Notification</strong>"
     + "        </div>"
     + "        <!-- Content -->"
     + "        <div class=\"content\">"
     + "            <p>Dear Customer,</p>"
     + "            <p>Please find below the details of your bill:</p>"
     + "            <!-- Bill Details Table -->"
     + "            <table class=\"bill-details\">"
     + "                <tr>"
     + "                    <th>Bill ID</th>"
     + "                    <td>{{billId}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Bill Issued Date</th>"
     + "                    <td>{{issueDate}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Plan Name</th>"
     + "                    <td>{{planName}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Bill Cycle</th>"
     + "                    <td>{{billCycle}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Usage</th>"
     + "                    <td>{{Usage}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Total Charges</th>"
     + "                    <td>{{totalCharges}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Tax</th>"
     + "                    <td>{{tax}}</td>"
     + "                </tr>"
     + "                <tr>"
     + "                    <th>Final Amount</th>"
     + "                    <td>{{finalAmount}}</td>"
     + "                </tr><br>"
     + "                <tr>"
     + "                    <th>Due Date</th>"
     + "                    <td>{{dueDate}}</td>"
     + "                </tr>"
     + "            </table>"
     + "            <!-- Payment Button -->"
     + "            <p style=\"text-align: center;\">"
     + "                <a href=\"{{paymentLink}}\" class=\"button\">Pay Now</a>"
     + "            </p>"
     + "            <p>If you have already paid this bill, please disregard this email.</p>"
     + "            <p>Thank you for choosing our services.</p>"
     + "        </div>"
     + "        <!-- Footer -->"
     + "        <div class=\"footer\">"
     + "            <p>&copy; 2024 Your Company Name. All Rights Reserved.</p>"
     + "            <p>Contact us: <a href=\"mailto:support@yourcompany.com\">support@yourcompany.com</a></p>"
     + "        </div>"
     + "    </div>"
     + "</body>"
     + "</html>";
     
     
     String paymentSuccess = "<!DOCTYPE html>"
    		    + "<html lang=\"en\">"
    		    + "<head>"
    		    + "    <meta charset=\"UTF-8\">"
    		    + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    		    + "    <title>Payment Confirmation</title>"
    		    + "    <style>"
    		    + "        body {"
    		    + "            font-family: 'Roboto', Arial, sans-serif;"
    		    + "            background-color: #f3f4f6;"
    		    + "            margin: 0;"
    		    + "            padding: 0;"
    		    + "        }"
    		    + "        .email-container {"
    		    + "            max-width: 600px;"
    		    + "            margin: 20px auto;"
    		    + "            background: #ffffff;"
    		    + "            border-radius: 12px;"
    		    + "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);"
    		    + "            overflow: hidden;"
    		    + "        }"
    		    + "        .header {"
    		    + "            background: linear-gradient(135deg, #4caf50, #66bb6a);"
    		    + "            color: #ffffff;"
    		    + "            text-align: center;"
    		    + "            padding: 30px 20px;"
    		    + "        }"
    		    + "        .header h1 {"
    		    + "            margin: 0;"
    		    + "            font-size: 28px;"
    		    + "            font-weight: bold;"
    		    + "        }"
    		    + "        .content {"
    		    + "            padding: 25px 20px;"
    		    + "            color: #333333;"
    		    + "            line-height: 1.6;"
    		    + "        }"
    		    + "        .content p {"
    		    + "            margin: 15px 0;"
    		    + "        }"
    		    + "        .details {"
    		    + "            margin-top: 20px;"
    		    + "            padding: 20px;"
    		    + "            background-color: #f9f9f9;"
    		    + "            border: 1px solid #e0e0e0;"
    		    + "            border-radius: 8px;"
    		    + "        }"
    		    + "        .details p {"
    		    + "            margin: 8px 0;"
    		    + "            font-size: 16px;"
    		    + "        }"
    		    + "        .details span {"
    		    + "            color: #4caf50;"
    		    + "            font-weight: bold;"
    		    + "        }"
    		    + "        .footer {"
    		    + "            text-align: center;"
    		    + "            padding: 15px 20px;"
    		    + "            background: linear-gradient(135deg, #4caf50, #66bb6a);"
    		    + "            color: #ffffff;"
    		    + "            font-size: 14px;"
    		    + "        }"
    		    + "        .footer a {"
    		    + "            color: #ffffff;"
    		    + "            text-decoration: underline;"
    		    + "        }"
    		    + "    </style>"
    		    + "</head>"
    		    + "<body>"
    		    + "    <div class=\"email-container\">"
    		    + "        <div class=\"header\">"
    		    + "            <h1>Payment Confirmation</h1>"
    		    + "        </div>"
    		    + "        <div class=\"content\">"
    		    + "            <p>Dear <strong>{{customerName}}</strong>,</p>"
    		    + "            <p>We are thrilled to let you know that your payment has been successfully processed. Thank you for your trust and promptness.</p>"
    		    + "            <div class=\"details\">"
    		    + "                <p>Bill ID: <span>{{billId}}</span></p>"
    		    + "                <p>Amount Paid: <span>{{amountPaid}}</span></p>"
    		    + "                <p>Payment Date: <span>{{paymentDate}}</span></p>"
    		    + "            </div>"
    		    + "            <p>If you have any questions or need assistance, feel free to reach out to our support team at <a href=\"mailto:support@company.com\">support@company.com</a>.</p>"
    		    + "            <p>We appreciate your business and look forward to serving you again!</p>"
    		    + "        </div>"
    		    + "        <div class=\"footer\">"
    		    + "            &copy; 2024 <strong> OTBS </strong>. All rights reserved. | <a href=\"https://www.company.com\">Visit Our Website</a>"
    		    + "        </div>"
    		    + "    </div>"
    		    + "</body>"
    		    + "</html>";
     
     
     String dueBending = "<!DOCTYPE html>"
    		    + "<html lang=\"en\">"
    		    + "<head>"
    		    + "    <meta charset=\"UTF-8\">"
    		    + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    		    + "    <title>Bill Due Alert</title>"
    		    + "    <style>"
    		    + "        body {"
    		    + "            font-family: 'Arial', sans-serif;"
    		    + "            background-color: #eef2f3;"
    		    + "            margin: 0;"
    		    + "            padding: 0;"
    		    + "        }"
    		    + "        .email-container {"
    		    + "            max-width: 600px;"
    		    + "            margin: 20px auto;"
    		    + "            background: #ffffff;"
    		    + "            border-radius: 8px;"
    		    + "            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);"
    		    + "            overflow: hidden;"
    		    + "            border: 1px solid #dcdcdc;"
    		    + "        }"
    		    + "        .header {"
    		    + "            background-color: #4caf50;"
    		    + "            color: #ffffff;"
    		    + "            text-align: center;"
    		    + "            padding: 20px;"
    		    + "        }"
    		    + "        .header h1 {"
    		    + "            margin: 0;"
    		    + "            font-size: 24px;"
    		    + "            font-weight: bold;"
    		    + "        }"
    		    + "        .content {"
    		    + "            padding: 20px;"
    		    + "            color: #333333;"
    		    + "            line-height: 1.6;"
    		    + "        }"
    		    + "        .content p {"
    		    + "            margin: 15px 0;"
    		    + "        }"
    		    + "        .details {"
    		    + "            margin: 20px 0;"
    		    + "            padding: 15px;"
    		    + "            background-color: #f9f9f9;"
    		    + "            border: 1px solid #e0e0e0;"
    		    + "            border-radius: 8px;"
    		    + "        }"
    		    + "        .details p {"
    		    + "            margin: 8px 0;"
    		    + "            font-size: 16px;"
    		    + "        }"
    		    + "        .details span {"
    		    + "            color: #4caf50;"
    		    + "            font-weight: bold;"
    		    + "        }"
    		    + "        .button-container {"
    		    + "            text-align: center;"
    		    + "            margin-top: 20px;"
    		    + "        }"
    		    + "        .button-container a {"
    		    + "            display: inline-block;"
    		    + "            padding: 10px 20px;"
    		    + "            background-color: #4caf50;"
    		    + "            color: #ffffff;"
    		    + "            text-decoration: none;"
    		    + "            border-radius: 4px;"
    		    + "            font-size: 16px;"
    		    + "            font-weight: bold;"
    		    + "        }"
    		    + "        .button-container a:hover {"
    		    + "            background-color: #45a049;"
    		    + "        }"
    		    + "        .footer {"
    		    + "            text-align: center;"
    		    + "            padding: 15px;"
    		    + "            background-color: #4caf50;"
    		    + "            color: #ffffff;"
    		    + "            font-size: 14px;"
    		    + "        }"
    		    + "        .footer a {"
    		    + "            color: #ffffff;"
    		    + "            text-decoration: underline;"
    		    + "        }"
    		    + "    </style>"
    		    + "</head>"
    		    + "<body>"
    		    + "    <div class=\"email-container\">"
    		    + "        <div class=\"header\">"
    		    + "            <h1>Bill Due Alert</h1>"
    		    + "        </div>"
    		    + "        <div class=\"content\">"
    		    + "            <p>Dear <strong>{{customerName}}</strong>,</p>"
    		    + "            <p>This is a friendly reminder that your bill's due date is just <b> 3 </b> days away. Please ensure timely payment to avoid any penalties.</p>"
    		    + "            <div class=\"details\">"
    		    + "                <p>Bill ID: <span>{{billId}}</span></p>"
    		    + "                <p>Amount Due: <span>{{amount}}</span></p>"
    		    + "                <p>Due Date: <span>{{dueDate}}</span></p>"
    		    + "            </div>"
    		    + "            <div class=\"button-container\">"
    		    + "                <a href=\"https://www.company.com/pay-now\">Pay Your Bill</a>"
    		    + "            </div>"
    		    + "            <p>If you have any questions, feel free to contact our support team at <a href=\"mailto:support@company.com\">support@company.com</a>.</p>"
    		    + "        </div>"
    		    + "        <div class=\"footer\">"
    		    + "            &copy; 2024 <strong> OTBS </strong>. All rights reserved."
    		    + "        </div>"
    		    + "    </div>"
    		    + "</body>"
    		    + "</html>";


}
